### PR TITLE
895 export base pair lines

### PR DESCRIPTION
**Pull request by RayBipse**
Added export SVG support for base pair lines.

## Changes
- Removed the old method of creating a separate method to filter selected base pairs as suggested.
- Modified ``_base_pairs(bool allow_mismatches)`` to ``_base_pairs(bool allow_mismatches, BuiltSet<Strand> selected_strands)``. Now base_pairs is ``this._base_pairs(false, strands.toBuiltSet())`` and ``selected_base_pairs(BuiltSet<Strand> selected_strands)`` just calls ``_base_pairs`` directly.
- For each base pair, I added an id ``base_pair-{helix-id}-{offset}`` so we can identify the base pairs that is in ``selected_base_pairs``.
- Created a new method ``List<Element> get_selected_base_pairs(Store<AppState> store)`` that mirrors the behavior of ``List<Element> get_selected_strands(Store<AppState> store)`` so that it adds the base pair HTML elements into the exported SVG.

### CODE REVIEW

**Review by dave-doty — CHANGES_REQUESTED** [review]
I don't know why, but it's not working for me. I create this design:

image

Then select and copy image:

image

But when I paste into Powerpoint, no base pair lines:

image

It **does** work if I Export an SVG file:

image


Open the SVG file in Inkscape:

image

**Comment by RayBipse** [comment]
It should work now. It was a quick fix. In ``export_svg_middleware``, there is an if statement. One branch is for ``ExportSvg`` and another is ``CopySelectedStandsToClipboardImage``. I just had to call ``get_selected_base_pairs`` in both branches.

**Comment by RayBipse** [comment]
The [new commit](https://github.com/UC-Davis-molecular-computing/scadnano/commit/94c0b0f3e3e368bbb60f114b8f86d3cc30b1bc33) renamed ``get_selected_strands`` and ``get_selected_base_pairs`` to ``get_svg_elements_of_strands`` and ``get_svg_elements_of_base_pairs`` as well as changes to function arguments. I also removed the long one-line and refactored two pieces of repeated of code into one function called ``get_selected_svg_elements``.

**Review by dave-doty — APPROVED** [review]

**Review by dave-doty — APPROVED** [review]
I don't know why I didn't approve this last month. I'll approve it for now since it seems to look okay, hopefully there's not something I missed that needs to be done still.

**Pull request merged**
