### PR TITLE
Work In Progress: Update dependencies and Dart SDK in workflows

### PR DESCRIPTION
**Pull request by UnHumbleBen**
Testing Dart CI workflow by triggering it through this pull request

### CODE REVIEW

**Comment by UnHumbleBen** [comment]
## Description
Updated dependencies in response to OverReact upgrade to version 4.2.6.

scadnano workflows will now use Dart SDK 2.13 instead of 2.9 because [Dart SDK 2.9 is no longer supported by OverReact](https://github.com/Workiva/over_react/pull/709). Dart SDK 2.13 is the newest SDK supported by OverReact because newer versions rely on analyzer 1.x, which OverReact does not support as noted [in the OverReact workflow file](https://github.com/Workiva/over_react/blob/7ee4fc2c07761a02d0f0a9577c4296b7a10e41a9/.github/workflows/dart_ci.yml#L18-L21).

react_components_test_template.html [has been updated](https://github.com/UC-Davis-molecular-computing/scadnano/pull/730/files#diff-51973b8c62e9893354828e73abdeddc3d0f7955f0175cb070364c8aae71118fdL7-R10) in response to [upgrading test_html_builder from version 1 to version 2](https://github.com/Workiva/test_html_builder/blob/2.0.0/CHANGELOG.md#200).

Lastly, to ensure that our developers are working on the app with the exact same versions, I committed the pubspec.lock file. This is recommended for application packages, as noted in the [Dart documentation](https://dart.dev/guides/libraries/private-files#pubspeclock).

## Related Issue
#706 

## How Has This Been Tested?
- [x] Ran unit tests locally
- [x] Run Dart CI workflow
- [ ] Run github-pages-dev workflow on fork
- [ ] Run github-pages workflow on fork
- [ ] Have @dave-doty test out the changes by pulling this branch and see if he can still run webdev serve and unit tests.

**Comment by dave-doty** [comment]
Do you think we should change this line:

```yaml
environment:
  sdk: '>=2.9.0 <3.0.0'
```

to

```yaml
environment:
  sdk: '>=2.11.0 <3.0.0'
```

Since OverReact is going to require `>=2.11` anyway?

**Comment by dave-doty** [comment]
I am able to rub locally after running 

```
pub get
```

then 

```
webdev serve
```

It's annoying that we still get the analyzer warning:

image

But it appears that OverReact is still requiring the old version of analyzer: 

https://github.com/Workiva/over_react/blob/7ee4fc2c07761a02d0f0a9577c4296b7a10e41a9/pubspec.yaml#L8-L13

**Comment by UnHumbleBen** [comment]
@dave-doty Updated SDK requirement in pubspec.yaml and fixed and tested the Github workflows, as indicated [above](https://github.com/UC-Davis-molecular-computing/scadnano/pull/730#issuecomment-1015104191). Ready to merge as soon as changes are approved.

**Review by dave-doty — APPROVED** [review]

**Pull request merged**
