### PR TITLE
make default max_offset on every helix equal to the max end of domain on any helix; closes #351

### LINKED ISSUE #351: make default max_offset on every helix equal to the max end of domain on any helix
Currently, if `Helix.max_offset` is not specified in the JSON, it defaults to the max `Domain.end` of any Domain on that Helix. This leads to ugly helices like this:

image

Instead, make max_offset the same for every Helix, like this:

image

### PR DESCRIPTION
**Pull request by rishabhmudradi**
If the max_offsets of helices are not specified, make the max_offset the same for every helix (by setting it equal to the max end of domain).

### CODE REVIEW

**Comment by dave-doty** [comment]
I made a mess of the dev and master branches today. Ben and I are going to try  to fix it later tonight. Until then, I'll leave this PR where it is.

**Comment by rishabhmudradi** [comment]
When the tests ran they failed and threw an "Instance of 'IllegalDNADesignError'" error. Not sure if this means there is an issue with my code, or if it was caused by committing.

**Comment by dave-doty** [comment]
At this point, who knows. I made a mess of things this morning. My goal is to get the dev (and eventually master) branches to look like this commit: https://github.com/UC-Davis-molecular-computing/scadnano/commit/52a03ca2cbbcc5e1029a038691b659a461cfc64f But my naive attempt to do so (doing a PR to merge that commit into dev) fails to actually get all of the changes into dev.

**Comment by dave-doty** [comment]
Sorry, it appears that this is going to clobber most of the changes I made in the past week. This is probably my fault from the mess I made this morning. But if you look at the "files changed" tab, it's going to change 48 files and undo a lot of stuff.

Sorry if this is extra work, but it's probably best to just start over and make a brand-new branch, after pull the latest dev branch.

**Pull request closed without merging**
