### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by UnHumbleBen**
See ~~#195~~ https://github.com/UC-Davis-molecular-computing/scadnano-python-package/pull/195

### CODE REVIEW

**Comment by dave-doty** [comment]
> See #195

Is that a typo? That seems like an old unrelated PR.

**Comment by dave-doty** [comment]
Is the effect this will have that when we make a PR, it automatically inserts the headers in the `pull_request_template.md` file?

Or is it just a template from which to manually copy and paste?

**Review by dave-doty — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by UnHumbleBen** [comment]
> > See #195
> 
> Is that a typo? That seems like an old unrelated PR.

Yes it was a typo, meant to link from scadnano python package: https://github.com/UC-Davis-molecular-computing/scadnano-python-package/pull/195

**Comment by UnHumbleBen** [comment]
> Is the effect this will have that when we make a PR, it automatically inserts the headers in the `pull_request_template.md` file?
> 
> Or is it just a template from which to manually copy and paste?
> 
> In either case, can we add documentation to CONTRIBUTING.md indicating what to do when making a PR? (either fill in the automatically provided template, or copy/paste from the template.)

It's automatic, I will add this to the CONTRIBUTING.md file

**Comment by UnHumbleBen** [comment]
Tested on Fork:
https://github.com/scadnano-test-pull-request-template/scadnano/compare/dev...test-pull-request-template?quick_pull=1

**Comment by UnHumbleBen** [comment]
> Is the effect this will have that when we make a PR, it automatically inserts the headers in the `pull_request_template.md` file?
> 
> Or is it just a template from which to manually copy and paste?
> 
> In either case, can we add documentation to CONTRIBUTING.md indicating what to do when making a PR? (either fill in the automatically provided template, or copy/paste from the template.)

Wrote that user should fill out template to CONTRIBUTING.md

**Review by dave-doty — APPROVED** [review]

**Pull request merged**
