### PR TITLE
Fixes #500; freeze versions in all GitHub actions

### LINKED ISSUE #500: freeze versions in all GitHub actions
Some GitHub actions get the latest versions (e.g., latest version of Dart). Instead, they should have a fixed version so that things don't change in deployment when a new version is released, and instead we should only update versions manually.

### PR DESCRIPTION
**Pull request by UnHumbleBen**

### CODE REVIEW

**Comment by UnHumbleBen** [comment]
I am stuck on why the CI is stuck when trying to compile the UT. Locally, the UT runs fine with dart version 2.9.3.

**Comment by dave-doty** [comment]
> I am confused on why the CI is stuck when trying to compile the UT. Locally, the UT runs fine with dart version 2.9.3.

Also the unit tests seem to be stuck (for 2 hours):

image

**Comment by UnHumbleBen** [comment]
> Also the unit tests seem to be stuck (for 2 hours):

Yes. This is what I meant by UT. I'm not sure what the cause could be. I am unable to reproduce this hanging issue on my local machine.

**Comment by UnHumbleBen** [comment]
Update: I am able to reproduce the hanging issue after running `pub upgrade`. Perhaps I was still using packages I installed with dart version 2.10.

**Comment by UnHumbleBen** [comment]
Alright looks like I finally have the correct version set. Just needed to upgrade build_runner. Awaiting your approval @dave-doty

**Review by dave-doty — APPROVED** [review]
Does this fix the GitHub pages deployment issue?

**Comment by UnHumbleBen** [comment]
Yup, it fixed in in my fork. Now to put it to the real test. Merging.

**Pull request merged**
