### PR TITLE
fixes #819 change color of warning star for domain name mismatch

### LINKED ISSUE #819: change color of warning star for domain name mismatch
It is too easy to confuse it with a DNA base mismatch; see issue #818.

This should be done by adding a prop `color` to `DesignMainWarningStar`, which is red for a DNA base mismatch but some other color for domain name mismatches. Perhaps blue or green, but it should be something that stands out in a large design and is easy to notice.

### PR DESCRIPTION
**Pull request by homaho1**

### CODE REVIEW

**Review by dave-doty — CHANGES_REQUESTED** [review]
This doesn't seem like a very extensible solution to go through CSS for the color. Is it possible to set the property directly in the React component? Then for the future we could add more colors more easily without having to edit the CSS style.

**Comment by homaho1** [comment]
I used `style` instead of `classname`. Is that the way you wanted it to be implemented?

**Comment by dave-doty** [comment]
> I used `style` instead of `classname`. Is this the way you wanted it to be implemented?

Sure, as long as it's straightforward to use a new color if we want and only have to change that one React prop.

**Review by dave-doty — APPROVED** [review]

**Comment by homaho1** [comment]
No problem. Should I go ahead and merge pull request?

**Comment by dave-doty** [comment]
Yes

**Pull request merged**
