### PR TITLE
Copy image of selected objects #740

### PR DESCRIPTION
**Pull request by sarahayu**

### CODE REVIEW

**Review by dave-doty — CHANGES_REQUESTED** [review]
Hmm, I'm not sure exactly how this is implemented, but it isn't doing quite what I want. It is possible somehow to move SVG objects with the copy buffer. For example, you can copy SVG from one instance of Inkscape and paste into another instance of Inkscape, or even into Powerpoint (and vice versa), and it preserves all the SVG structure (groups and so forth). 

This implementation just copies a non-vector graphics image. I can copy from scadnano and paste into Inkscape or Powerpoint, but it does not preserve the SVG structure. I cannot copy several strands and then ungroup them to move them around. If I zoom in on Inkscape, the image is pixelated:

image


And if I look at the SVG source, it's an `img` object, not the original SVG:

image

It should be possible to copy the SVG directly. For instance, if I make these 16 squares in Inkscape and group them:

image

I can copy/paste it from Inkscape into Powerpoint, where I can then ungroup them (after responding "yes" to Powerpoint's request for me to convert the image into a drawing object):

image

Hopefully we should be able to use the same technique (whatever it is that lets you copy/paste between Inkscape and Powerpoint and preserve the structured vector graphics).

**Comment by sarahayu** [comment]
It appears Chrome's clipboard and SVGs don't work well together (apparently for security reasons): [https://stackoverflow.com/a/31287434](https://stackoverflow.com/a/31287434)
The answer links to a Chromium bug report, the [latest comment ](https://bugs.chromium.org/p/chromium/issues/detail?id=504700#c9) by someone trying to do the same as us in copying an SVG to the clipboard. They said it has worked for them in Firefox, but I've tried changing our code to set the mime-type to image/svg+xml and tested it in Firefox to no avail.
We might just have to put this issue on standby until a workaround can be found?

**Comment by dave-doty** [comment]
> It appears Chrome's clipboard and SVGs don't work well together (apparently for security reasons): https://stackoverflow.com/a/31287434 The answer links to a Chromium bug report, the [latest comment ](https://bugs.chromium.org/p/chromium/issues/detail?id=504700#c9) by someone trying to do the same as us in copying an SVG to the clipboard. They said it has worked for them in Firefox, but I've tried changing our code to set the mime-type to image/svg+xml and tested it in Firefox to no avail. We might just have to put this issue on standby until a workaround can be found?

Yeah, this is frustrating. I've searched google for any hint as to what exactly Inkscape and Powerpoint do to modify the copy buffer so that you can copy/paste SVG objects between them. Still no idea. Obviously it's there in the source code of Inkscape somewhere, but I don't know where to look. It's definitely not text. If you copy an Inkscape object and paste into a text editor, nothing happens.

**Comment by abhishekgokhale** [comment]
Resolved conflict and formatted old code from this branch, branch should be good to be merged into dev with Ctrl/Cmd + I giving the PNG image on the clipboard

**Review by dave-doty — APPROVED** [review]

**Pull request merged**
